### ISSUE TITLE
Which version of scrapy should we use?

### ISSUE THREAD

**Issue by morpheuslord** [ahmia/ahmia-crawler#51]
I am facing this weird issue while running the crawler on a docker instance:
```sh
Scrapy 2.9.0 - no active project

Unknown command: crawl

Use "scrapy" to see available commands
```

I also tried the `2.11.2` version and the same issue persists, can someone share which version works the best.

**Comment by samip5** [comment]
You're missing the scrapy.cfg config, as otherwise you will get that. https://github.com/ahmia/ahmia-crawler/blob/master/ahmia/scrapy.cfg

**Comment by juhanurmi** [comment]
It is now Scrapy==2.11.2 in requirements.txt.
https://github.com/ahmia/ahmia-crawler/blob/master/requirements.txt
