### ISSUE TITLE
port to python3

### ISSUE THREAD

**Issue by hysia** [ahmia/ahmia-crawler#7]
https://github.com/ahmia/ahmia-crawler/blob/0ec3be0bfe70c3fda6a58c617c43126f9f0d34fd/ahmia/ahmia/spiders/base.py#L128

should be：
`hash_target = hashlib.sha1(request.url.encode('utf-8')).hexdigest()`

**Comment by chefarov** [comment]
Thank you for noting @hysia 

Fixed in [tsop18:acfcfe1](https://github.com/ahmia/ahmia-crawler/commit/acfcfe1a5a6a11785921068651bc38bfcc487444)
